// Generated by CoffeeScript 1.9.3
(function() {
  var T;

  T = require('../node_modules/timbre');

  (T("audio")).load("../misc/audio/amen.wav", function() {
    return this.play();
  });

}).call(this);
