// Generated by CoffeeScript 1.9.3
(function() {
  var VoiceText, fs, voice;

  require('/Users/webos/.nvm/versions/node/v0.12.7/lib/node_modules/coffee-script/register');

  fs = require('fs');

  VoiceText = require('../node_modules/voicetext');

  voice = new VoiceText('jdd58fkejgh09lyb');

  voice.speaker(voice.SPEAKER.HIKARI).speak('おはようございます', function(e, buf) {
    if (e) {
      console.error(e);
    }
    return fs.writeFile('./test.wav', buf, 'binary', function(e) {
      if (e) {
        return console.error(e);
      }
    });
  });

}).call(this);
